model_type: regimes
enabled_assets: [WORLD, SP500, NASDAQ100]
regimes:
  - name: calm
    mu_multiplier: 1.0
    sigma_multiplier: 1.0
    corr_multiplier: 1.0
  - name: crisis
    mu_multiplier: 0.0
    sigma_multiplier: 2.0
    corr_multiplier: 1.2
transition_matrix:
  - [0.98, 0.02]
  - [0.10, 0.90]
initial_probs: [0.9, 0.1]
